workflows:
  ios-publish:
    name: iOS Publish to App Store
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      # Apenas as configurações de ambiente
      node: 20
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Instalar dependências e construir o projeto web
        script: |
          npm install
          npm run build
          
      - name: Adicionar e sincronizar a plataforma iOS com Capacitor
        script: |
          npx cap add ios || true
          npx cap sync ios
          
      - name: Configurar Versão e Build Number
        script: |
          # Define a versão e o build number no projeto Xcode
          cd ios
          agvtool new-marketing-version $APP_VERSION
          agvtool new-version -all $BUILD_NUMBER
          cd ..
          
      - name: Configurar o Provisionamento Automático
        script: |
          # As variáveis $BUNDLE_ID, $APP_VERSION, $BUILD_NUMBER virão da interface do Codemagic
          app-store-connect fetch-signing-files $BUNDLE_ID \
            --type IOS_APP_STORE \
            --platform IOS \
            --create-profiles \
            --use-api-key
            
      - name: Configurar o Xcode para Assinatura
        script: |
          xcode-project use-profiles
          
      - name: Build do Aplicativo iOS
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcodeproj" \
            --scheme "App"
            
    artifacts:
      - build/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      app_store_connect:
        api_key:
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          key_id: $APP_STORE_CONNECT_KEY_ID
          private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        
        submit_for_review: true
        teams:
          - lubatechnoloy@gmail.com
        release_notes:
          en-US: "Primeira versão do Metafit Nutri."
          pt-BR: "Primeira versão do Metafit Nutri."
