-- Create table for personal trainer students
CREATE TABLE public.trainer_students (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  trainer_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  age INTEGER,
  weight NUMERIC,
  height NUMERIC,
  goal TEXT NOT NULL CHECK (goal IN ('lose_weight', 'gain_weight', 'maintain')),
  activity_level TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.trainer_students ENABLE ROW LEVEL SECURITY;

-- Trainers can only see their own students
CREATE POLICY "Trainers can view own students"
ON public.trainer_students
FOR SELECT
USING (auth.uid() = trainer_id);

CREATE POLICY "Trainers can insert own students"
ON public.trainer_students
FOR INSERT
WITH CHECK (auth.uid() = trainer_id);

CREATE POLICY "Trainers can update own students"
ON public.trainer_students
FOR UPDATE
USING (auth.uid() = trainer_id);

CREATE POLICY "Trainers can delete own students"
ON public.trainer_students
FOR DELETE
USING (auth.uid() = trainer_id);

-- Create trigger for updated_at
CREATE TRIGGER update_trainer_students_updated_at
BEFORE UPDATE ON public.trainer_students
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Create table for student plans generated by trainer
CREATE TABLE public.student_plans (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  student_id UUID NOT NULL REFERENCES public.trainer_students(id) ON DELETE CASCADE,
  trainer_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  plan_type TEXT NOT NULL CHECK (plan_type IN ('workout', 'meal')),
  plan_data JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.student_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Trainers can view own student plans"
ON public.student_plans
FOR SELECT
USING (auth.uid() = trainer_id);

CREATE POLICY "Trainers can insert own student plans"
ON public.student_plans
FOR INSERT
WITH CHECK (auth.uid() = trainer_id);

CREATE POLICY "Trainers can delete own student plans"
ON public.student_plans
FOR DELETE
USING (auth.uid() = trainer_id);